
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class AnimClipData : Luban.BeanBase
{
    public AnimClipData(JsonElement _buf) 
    {
        AnimPath = _buf.GetProperty("animPath").GetString();
        X = _buf.GetProperty("x").GetInt32();
        Y = _buf.GetProperty("y").GetInt32();
    }

    public static AnimClipData DeserializeAnimClipData(JsonElement _buf)
    {
        return new AnimClipData(_buf);
    }

    public readonly string AnimPath;
    public readonly int X;
    public readonly int Y;
   
    public const int __ID__ = 2083108971;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "animPath:" + AnimPath + ","
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }
}

}
