
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Audio : Luban.BeanBase
{
    public Audio(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        CharacterId = _buf.GetProperty("characterId").GetInt32();
        SkillId = _buf.GetProperty("skillId").GetInt32();
        StateId = _buf.GetProperty("stateId").GetInt32();
        Keyword = _buf.GetProperty("keyword").GetString();
        PlayMode = _buf.GetProperty("playMode").GetInt32();
        { var __json0 = _buf.GetProperty("audioDatas"); AudioDatas = new System.Collections.Generic.List<AudioData>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { AudioData __v0;  __v0 = AudioData.DeserializeAudioData(__e0);  AudioDatas.Add(__v0); }   }
    }

    public static Audio DeserializeAudio(JsonElement _buf)
    {
        return new Audio(_buf);
    }

    public readonly int Id;
    public readonly int CharacterId;
    public readonly int SkillId;
    public readonly int StateId;
    public readonly string Keyword;
    public readonly int PlayMode;
    /// <summary>
    /// audioName
    /// </summary>
    public readonly System.Collections.Generic.List<AudioData> AudioDatas;
   
    public const int __ID__ = 63613878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        foreach (var _e in AudioDatas) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterId:" + CharacterId + ","
        + "skillId:" + SkillId + ","
        + "stateId:" + StateId + ","
        + "keyword:" + Keyword + ","
        + "playMode:" + PlayMode + ","
        + "audioDatas:" + Luban.StringUtil.CollectionToString(AudioDatas) + ","
        + "}";
    }
}

}
