
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class AudioData : Luban.BeanBase
{
    public AudioData(JsonElement _buf) 
    {
        AudioName = _buf.GetProperty("audioName").GetString();
        SourceType = (AudioSourceType)_buf.GetProperty("sourceType").GetInt32();
        PlayType = _buf.GetProperty("playType").GetInt32();
        Volume = _buf.GetProperty("volume").GetSingle();
        Speed = _buf.GetProperty("speed").GetSingle();
        Loop = _buf.GetProperty("loop").GetBoolean();
        OnlySelf = _buf.GetProperty("onlySelf").GetBoolean();
        Delay = _buf.GetProperty("delay").GetSingle();
        Weight = _buf.GetProperty("weight").GetSingle();
        MaxLoopTime = _buf.GetProperty("maxLoopTime").GetSingle();
    }

    public static AudioData DeserializeAudioData(JsonElement _buf)
    {
        return new AudioData(_buf);
    }

    public readonly string AudioName;
    public readonly AudioSourceType SourceType;
    public readonly int PlayType;
    public readonly float Volume;
    public readonly float Speed;
    public readonly bool Loop;
    public readonly bool OnlySelf;
    public readonly float Delay;
    public readonly float Weight;
    public readonly float MaxLoopTime;
   
    public const int __ID__ = -2103294848;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "audioName:" + AudioName + ","
        + "sourceType:" + SourceType + ","
        + "playType:" + PlayType + ","
        + "volume:" + Volume + ","
        + "speed:" + Speed + ","
        + "loop:" + Loop + ","
        + "onlySelf:" + OnlySelf + ","
        + "delay:" + Delay + ","
        + "weight:" + Weight + ","
        + "maxLoopTime:" + MaxLoopTime + ","
        + "}";
    }
}

}
