
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Character : Luban.BeanBase
{
    public Character(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        HeadIcon = _buf.GetProperty("headIcon").GetString();
        ModePath = _buf.GetProperty("modePath").GetString();
        PropertyId = _buf.GetProperty("propertyId").GetInt32();
        { var __json0 = _buf.GetProperty("skills"); Skills = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Skills.Add(__v0); }   }
        StateAnims = _buf.GetProperty("stateAnims").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        IsFake = _buf.GetProperty("isFake").GetBoolean();
    }

    public static Character DeserializeCharacter(JsonElement _buf)
    {
        return new Character(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 角色头像地址
    /// </summary>
    public readonly string HeadIcon;
    /// <summary>
    /// 角色模型
    /// </summary>
    public readonly string ModePath;
    /// <summary>
    /// 角色属性
    /// </summary>
    public readonly int PropertyId;
    /// <summary>
    /// 角色技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 状态动画
    /// </summary>
    public readonly string StateAnims;
    /// <summary>
    /// 角色描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 是否为假人
    /// </summary>
    public readonly bool IsFake;
   
    public const int __ID__ = -726803703;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "headIcon:" + HeadIcon + ","
        + "modePath:" + ModePath + ","
        + "propertyId:" + PropertyId + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "stateAnims:" + StateAnims + ","
        + "desc:" + Desc + ","
        + "isFake:" + IsFake + ","
        + "}";
    }
}

}
