
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Property : Luban.BeanBase
{
    public Property(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Hp = _buf.GetProperty("hp").GetInt32();
        Atk = _buf.GetProperty("atk").GetInt32();
        Defend = _buf.GetProperty("defend").GetInt32();
        MoveSpeed = _buf.GetProperty("moveSpeed").GetSingle();
        AtkSpeed = _buf.GetProperty("atkSpeed").GetSingle();
    }

    public static Property DeserializeProperty(JsonElement _buf)
    {
        return new Property(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Atk;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Defend;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 攻击速度
    /// </summary>
    public readonly float AtkSpeed;
   
    public const int __ID__ = -928497163;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "atk:" + Atk + ","
        + "defend:" + Defend + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "atkSpeed:" + AtkSpeed + ","
        + "}";
    }
}

}
