
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum StateExitType
    {
        /// <summary>
        /// 定时预测退出
        /// </summary>
        TIME_EXIT = 1,
        /// <summary>
        /// 无预测退出
        /// </summary>
        UNKOWN_EXIT = 2,
        /// <summary>
        /// 可变定时预测退出
        /// </summary>
        CHANGE_TIME_EXIT = 3,
    }

} 

