
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public partial class TbAnimation
{
    private readonly System.Collections.Generic.Dictionary<string, Animation> _dataMap;
    private readonly System.Collections.Generic.List<Animation> _dataList;
    
    public TbAnimation(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Animation>();
        _dataList = new System.Collections.Generic.List<Animation>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Animation _v;
            _v = Animation.DeserializeAnimation(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Animation> DataMap => _dataMap;
    public System.Collections.Generic.List<Animation> DataList => _dataList;

    public Animation GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Animation Get(string key) => _dataMap[key];
    public Animation this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
