
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public partial class TbCharacter
{
    private readonly System.Collections.Generic.Dictionary<int, Character> _dataMap;
    private readonly System.Collections.Generic.List<Character> _dataList;
    
    public TbCharacter(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Character>();
        _dataList = new System.Collections.Generic.List<Character>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Character _v;
            _v = Character.DeserializeCharacter(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character> DataMap => _dataMap;
    public System.Collections.Generic.List<Character> DataList => _dataList;

    public Character GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character Get(int key) => _dataMap[key];
    public Character this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
