
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public partial class TbProperty
{
    private readonly System.Collections.Generic.Dictionary<int, Property> _dataMap;
    private readonly System.Collections.Generic.List<Property> _dataList;
    
    public TbProperty(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Property>();
        _dataList = new System.Collections.Generic.List<Property>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Property _v;
            _v = Property.DeserializeProperty(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Property> DataMap => _dataMap;
    public System.Collections.Generic.List<Property> DataList => _dataList;

    public Property GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Property Get(int key) => _dataMap[key];
    public Property this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
