
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class TbItem2
{
    private readonly System.Collections.Generic.Dictionary<int, Item2> _dataMap;
    private readonly System.Collections.Generic.List<Item2> _dataList;
    
    public TbItem2(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Item2>();
        _dataList = new System.Collections.Generic.List<Item2>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Item2 _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Item2.DeserializeItem2(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item2> DataMap => _dataMap;
    public System.Collections.Generic.List<Item2> DataList => _dataList;

    public Item2 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item2 Get(int key) => _dataMap[key];
    public Item2 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
