
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class AnimClipData : Luban.BeanBase
{
    public AnimClipData(JSONNode _buf) 
    {
        { if(!_buf["animPath"].IsString) { throw new SerializationException(); }  AnimPath = _buf["animPath"]; }
        { if(!_buf["realLength"].IsNumber) { throw new SerializationException(); }  RealLength = _buf["realLength"]; }
        { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
        { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
    }

    public static AnimClipData DeserializeAnimClipData(JSONNode _buf)
    {
        return new AnimClipData(_buf);
    }

    public readonly string AnimPath;
    public readonly float RealLength;
    public readonly int X;
    public readonly int Y;
   
    public const int __ID__ = 2083108971;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "animPath:" + AnimPath + ","
        + "realLength:" + RealLength + ","
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }
}

}
