
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum AudioSourceType
    {
        /// <summary>
        /// 默认音源
        /// </summary>
        DEFAULT = 1,
        /// <summary>
        /// 音源来自角色嘴巴
        /// </summary>
        CHARACTER_MOUTH = 2,
        /// <summary>
        /// 音源来自角色身体
        /// </summary>
        CHARACTER_BODY = 3,
        /// <summary>
        /// 音源来自技能
        /// </summary>
        SKILL = 4,
    }

} 

