
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Character : Luban.BeanBase
{
    public Character(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["modePath"].IsString) { throw new SerializationException(); }  ModePath = _buf["modePath"]; }
        { if(!_buf["propertyId"].IsNumber) { throw new SerializationException(); }  PropertyId = _buf["propertyId"]; }
        { var __json0 = _buf["skills"]; if(!__json0.IsArray) { throw new SerializationException(); } Skills = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills.Add(__v0); }   }
        { if(!_buf["stateAnims"].IsString) { throw new SerializationException(); }  StateAnims = _buf["stateAnims"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["isFake"].IsBoolean) { throw new SerializationException(); }  IsFake = _buf["isFake"]; }
    }

    public static Character DeserializeCharacter(JSONNode _buf)
    {
        return new Character(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 角色模型
    /// </summary>
    public readonly string ModePath;
    /// <summary>
    /// 角色属性
    /// </summary>
    public readonly int PropertyId;
    /// <summary>
    /// 角色技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 状态动画
    /// </summary>
    public readonly string StateAnims;
    /// <summary>
    /// 角色描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 是否为假人
    /// </summary>
    public readonly bool IsFake;
   
    public const int __ID__ = -726803703;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "modePath:" + ModePath + ","
        + "propertyId:" + PropertyId + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "stateAnims:" + StateAnims + ","
        + "desc:" + Desc + ","
        + "isFake:" + IsFake + ","
        + "}";
    }
}

}
