
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Property : Luban.BeanBase
{
    public Property(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["atk"].IsNumber) { throw new SerializationException(); }  Atk = _buf["atk"]; }
        { if(!_buf["defend"].IsNumber) { throw new SerializationException(); }  Defend = _buf["defend"]; }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["moveSpeed"]; }
        { if(!_buf["atkSpeed"].IsNumber) { throw new SerializationException(); }  AtkSpeed = _buf["atkSpeed"]; }
    }

    public static Property DeserializeProperty(JSONNode _buf)
    {
        return new Property(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Atk;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Defend;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 攻击速度
    /// </summary>
    public readonly float AtkSpeed;
   
    public const int __ID__ = -928497163;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "atk:" + Atk + ","
        + "defend:" + Defend + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "atkSpeed:" + AtkSpeed + ","
        + "}";
    }
}

}
