
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillTags
    {
        /// <summary>
        /// 伤害类
        /// </summary>
        DAMAGE_TAG = 1,
        /// <summary>
        /// 恢复类
        /// </summary>
        RECOVER_TAG = 2,
        /// <summary>
        /// 增益类
        /// </summary>
        BUFF_TAG = 3,
        /// <summary>
        /// 减益类
        /// </summary>
        DEBUFF_TAG = 4,
        /// <summary>
        /// 位移类
        /// </summary>
        MOVE_POS_TAG = 5,
        /// <summary>
        /// 脱手类
        /// </summary>
        OUT_HAND_TAG = 6,
    }

} 

